version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@11.6.1
  shellcheck: circleci/shellcheck@3.1

filters: &filters
  tags:
    only: /.*/

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/review:
          filters: *filters
      - shellcheck/check:
          filters: *filters
      # - orb-tools/publish:
      #     context: orb-publishing
      #     filters:
      #       tags:
      #         only: /.*/
      #     orb-name: govstack-working-group/testutils
      #     requires:
      #       - orb-tools/lint
      #       - orb-tools/review
      #       - orb-tools/pack
      #       - shellcheck/check
      #     vcs-type: << pipeline.project.type >>
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          pipeline-number: << pipeline.number >>
          vcs-type: << pipeline.project.type >>
          # requires: [orb-tools/publish]
          requires:
            - orb-tools/lint
            - orb-tools/review
            - orb-tools/pack
            - shellcheck/check
          filters: *filters
